title: Intelligent Information Processing 2023-I
description: Pingdingshan University, Pingdingshan, China
sitename: Machine Learning
baseurl: '/iip-2023-1'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
